version: "2"
services:
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
  app:
    container_name: api
    restart: always
    build: .
    ports:
      - "8080:8080"
    links:
      - mongo
